# generated by datamodel-codegen:
#   filename:  instantActions.schema
#   timestamp: 2025-02-04T08:14:08+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Optional, Union

from pydantic import BaseModel, Field


class BlockingType(Enum):
    NONE = "NONE"
    SOFT = "SOFT"
    HARD = "HARD"


class ActionParameter(BaseModel):
    key: str = Field(
        ...,
        description="The key of the action parameter.",
        examples=["duration", "direction", "signal"],
    )
    value: Union[List[Any], bool, float, str] = Field(
        ...,
        description="The value of the action parameter",
        examples=[103.2, "left", True, ["arrays", "are", "also", "valid"]],
    )


class Action(BaseModel):
    actionName: str = Field(
        ...,
        description='Enum of actions as described in the first column of "Actions and Parameters"\nIdentifies the function of the action.',
        title="actionName",
    )
    actionId: str = Field(
        ..., description="ID to distinguish between multiple actions.", title="actionId"
    )
    actionDescription: Optional[str] = Field(
        None, title="Additional Information on the action"
    )
    blockingType: BlockingType = Field(
        ...,
        description="Regulates if the action is allowed to be executed during movement and/or parallel to other actions.\nnone: action can happen in parallel with others, including movement.\nsoft: action can happen simultaneously with others, but not while moving.\nhard: no other actions can be performed while this action is running.",
        title="blockingType",
    )
    actionParameters: Optional[List[ActionParameter]] = Field(
        None,
        description="Array of actionParameter-objects for the indicated action e. g. deviceId, loadId, external Triggers.",
    )


class InstantActions(BaseModel):
    headerId: Optional[int] = Field(
        None,
        description="headerId of the message. The headerId is defined per topic and incremented by 1 with each sent (but not necessarily received) message.",
        title="headerId",
    )
    timestamp: Optional[datetime] = Field(
        None,
        description="Timestamp in ISO8601 format.",
        examples=["1991-03-11T11:40:03.12Z"],
        title="timestamp",
    )
    version: Optional[str] = Field(
        None,
        description="Version of the protocol [Major].[Minor].[Patch]",
        examples=["1.3.2"],
        title="Version",
    )
    manufacturer: Optional[str] = Field(None, description="Manufacturer of the AGV")
    serialNumber: Optional[str] = Field(None, description="Serial number of the AGV.")
    actions: Optional[List[Action]] = None
