# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/VDA5050/VDA5050/main/json_schemas/order.schema
#   timestamp: 2024-08-30T05:49:50+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional, Union

from pydantic import BaseModel, Field, confloat, conint
import json


class NodePosition(BaseModel):
    x: float = Field(
        ...,
        description="X-position on the map in reference to the map coordinate system. Precision is up to the specific implementation.",
    )
    y: float = Field(
        ...,
        description="Y-position on the map in reference to the map coordinate system. Precision is up to the specific implementation.",
    )
    theta: Optional[confloat(ge=-3.14159265359, le=3.14159265359)] = Field(
        None,
        description="Absolute orientation of the AGV on the node. \nOptional: vehicle can plan the path by itself.\nIf defined, the AGV has to assume the theta angle on this node. If previous edge disallows rotation, the AGV must rotate on the node. If following edge has a differing orientation defined but disallows rotation, the AGV is to rotate on the node to the edges desired rotation before entering the edge.",
    )
    allowedDeviationXY: Optional[confloat(ge=0.0)] = Field(
        None,
        description="Indicates how exact an AGV has to drive over a node in order for it to count as traversed.\nIf = 0: no deviation is allowed (no deviation means within the normal tolerance of the AGV manufacturer).\nIf > 0: allowed deviation-radius in meters. If the AGV passes a node within the deviation-radius, the node is considered to have been traversed.",
    )
    allowedDeviationTheta: Optional[confloat(ge=-3.141592654, le=3.141592654)] = Field(
        None,
        description="Indicates how big the deviation of theta angle can be. \nThe lowest acceptable angle is theta - allowedDeviationTheta and the highest acceptable angle is theta + allowedDeviationTheta.",
    )
    mapId: str = Field(
        ...,
        description="Unique identification of the map in which the position is referenced.\nEach map has the same origin of coordinates. When an AGV uses an elevator, e.g., leading from a departure floor to a target floor, it will disappear off the map of the departure floor and spawn in the related lift node on the map of the target floor.",
    )
    mapDescription: Optional[str] = Field(
        None, description="Additional information on the map."
    )


class ControlPoint(BaseModel):
    x: float = Field(
        ..., description="X coordinate described in the world coordinate system."
    )
    y: float = Field(
        ..., description="Y coordinate described in the world coordinate system."
    )
    weight: Optional[confloat(ge=0.0)] = Field(
        None,
        description="The weight, with which this control point pulls on the curve. When not defined, the default will be 1.0.",
    )


class Trajectory(BaseModel):
    degree: conint(ge=1) = Field(
        ...,
        description="Defines the number of control points that influence any given point on the curve. Increasing the degree increases continuity. If not defined, the default value is 1.",
    )
    knotVector: List[confloat(ge=0.0, le=1.0)] = Field(
        ...,
        description="Sequence of parameter values that determines where and how the control points affect the NURBS curve. knotVector has size of number of control points + degree + 1.",
    )
    controlPoints: List[ControlPoint] = Field(
        ...,
        description="List of JSON controlPoint objects defining the control points of the NURBS, which includes the beginning and end point.",
    )


class CorridorRefPoint(Enum):
    KINEMATICCENTER = "KINEMATICCENTER"
    CONTOUR = "CONTOUR"


class Corridor(BaseModel):
    leftWidth: confloat(ge=0.0) = Field(
        ...,
        description="Defines the width of the corridor in meters to the left related to the trajectory of the vehicle.",
    )
    rightWidth: confloat(ge=0.0) = Field(
        ...,
        description="Defines the width of the corridor in meters to the right related to the trajectory of the vehicle.",
    )
    corridorRefPoint: Optional[CorridorRefPoint] = Field(
        None,
        description="Defines whether the boundaries are valid for the kinematic center or the contour of the vehicle.",
    )


class BlockingType(Enum):
    NONE = "NONE"
    SOFT = "SOFT"
    HARD = "HARD"


class ActionParameter(BaseModel):
    key: str = Field(
        ...,
        description="The key of the action parameter.",
        examples=["duration", "direction", "signal"],
    )
    value: Union[List[Any], bool, float, str, Dict[str, Any]] = Field(
        ...,
        description="The value of the action parameter",
        examples=[103.2, "left", True, ["arrays", "are", "also", "valid"]],
    )


class Action(BaseModel):
    actionType: str = Field(
        ...,
        description='Name of action as described in the first column of "Actions and Parameters". Identifies the function of the action.',
    )
    actionId: str = Field(
        ...,
        description="Unique ID to identify the action and map them to the actionState in the state. Suggestion: Use UUIDs.",
    )
    actionDescription: Optional[str] = Field(
        None, description="Additional information on the action."
    )
    blockingType: BlockingType = Field(
        ...,
        description="Regulates if the action is allowed to be executed during movement and/or parallel to other actions.\nnone: action can happen in parallel with others, including movement.\nsoft: action can happen simultaneously with others, but not while moving.\nhard: no other actions can be performed while this action is running.",
    )
    actionParameters: Optional[List[ActionParameter]] = Field(
        None,
        description="Array of actionParameter-objects for the indicated action e. g. deviceId, loadId, external Triggers.",
    )


class Node(BaseModel):
    nodeId: str = Field(
        ...,
        description="Unique node identification",
        examples=["pumpenhaus_1", "MONTAGE"],
    )
    sequenceId: conint(ge=0) = Field(
        ...,
        description="Number to track the sequence of nodes and edges in an order and to simplify order updates.\nThe main purpose is to distinguish between a node which is passed more than once within one orderId. The variable sequenceId runs across all nodes and edges of the same order and is reset when a new orderId is issued.",
    )
    nodeDescription: Optional[str] = Field(
        None, description="Additional information on the node."
    )
    released: bool = Field(
        ...,
        description="True indicates that the node is part of the base. False indicates that the node is part of the horizon.",
    )
    nodePosition: Optional[NodePosition] = Field(
        None,
        description="Defines the position on a map in world coordinates. Each floor has its own map. All maps must use the same project specific global origin. \nOptional for vehicle-types that do not require the node position (e.g., line-guided vehicles).",
    )
    actions: List[Action] = Field(
        ...,
        description="Array of actions to be executed on a node. Empty array, if no actions required.",
    )


class Edge(BaseModel):
    edgeId: str = Field(..., description="Unique edge identification")
    sequenceId: conint(ge=0) = Field(
        ...,
        description="Number to track the sequence of nodes and edges in an order and to simplify order updates. The variable sequenceId runs across all nodes and edges of the same order and is reset when a new orderId is issued.",
    )
    edgeDescription: Optional[str] = Field(
        None, description="Additional information on the edge."
    )
    released: bool = Field(
        ...,
        description="True indicates that the edge is part of the base. False indicates that the edge is part of the horizon.",
    )
    startNodeId: str = Field(..., description="The nodeId of the start node.")
    endNodeId: str = Field(..., description="The nodeId of the end node.")
    maxSpeed: Optional[float] = Field(
        None,
        description="Permitted maximum speed on the edge in m/s. Speed is defined by the fastest measurement of the vehicle.",
    )
    maxHeight: Optional[float] = Field(
        None,
        description="Permitted maximum height of the vehicle, including the load, on edge in meters.",
    )
    minHeight: Optional[float] = Field(
        None,
        description="Permitted minimal height of the load handling device on the edge in meters",
    )
    orientation: Optional[confloat(ge=-3.14159265359, le=3.14159265359)] = Field(
        None,
        description="Orientation of the AGV on the edge. The value orientationType defines if it has to be interpreted relative to the global project specific map coordinate system or tangential to the edge. In case of interpreted tangential to the edge 0.0 = forwards and PI = backwards. Example: orientation Pi/2 rad will lead to a rotation of 90 degrees. \nIf AGV starts in different orientation, rotate the vehicle on the edge to the desired orientation if rotationAllowed is set to True. If rotationAllowed is False, rotate before entering the edge. If that is not possible, reject the order. \nIf no trajectory is defined, apply the rotation to the direct path between the two connecting nodes of the edge. If a trajectory is defined for the edge, apply the orientation to the trajectory.",
    )
    orientationType: Optional[str] = Field(
        None,
        description='Enum {GLOBALGLOBAL, TANGENTIALTANGENTIAL}: \n"GLOBAL"- relative to the global project specific map coordinate system; \n"TANGENTIAL"- tangential to the edge. \nIf not defined, the default value is "TANGENTIAL".',
    )
    direction: Optional[str] = Field(
        None,
        description="Sets direction at junctions for line-guided or wire-guided vehicles, to be defined initially (vehicle-individual).",
    )
    rotationAllowed: Optional[bool] = Field(
        None,
        description="True: rotation is allowed on the edge. False: rotation is not allowed on the edge. \nOptional: No limit, if not set.",
    )
    maxRotationSpeed: Optional[float] = Field(
        None,
        description="Maximum rotation speed in rad/s. \nOptional: No limit, if not set.",
    )
    length: Optional[float] = Field(
        None,
        description="Distance of the path from startNode to endNode in meters. \nOptional: This value is used by line-guided AGVs to decrease their speed before reaching a stop position.",
    )
    trajectory: Optional[Trajectory] = Field(
        None,
        description="Trajectory JSON-object for this edge as a NURBS. Defines the curve, on which the AGV should move between startNode and endNode. \nOptional: Can be omitted, if AGV cannot process trajectories or if AGV plans its own trajectory.",
    )
    corridor: Optional[Corridor] = Field(
        None,
        description="Definition of boundaries in which a vehicle can deviate from its trajectory, e. g. to avoid obstacles.",
    )
    actions: List[Action] = Field(
        ..., description="Array of action objects with detailed information."
    )


class OrderMessage(BaseModel):
    headerId: int = Field(
        ...,
        description="headerId of the message. The headerId is defined per topic and incremented by 1 with each sent (but not necessarily received) message.",
    )
    timestamp: datetime = Field(
        ...,
        description="Timestamp in ISO8601 format (YYYY-MM-DDTHH:mm:ss.ffZ).",
        examples=["1991-03-11T11:40:03.12Z"],
    )
    version: str = Field(
        ...,
        description="Version of the protocol [Major].[Minor].[Patch]",
        examples=["1.3.2"],
    )
    manufacturer: str = Field(..., description="Manufacturer of the AGV")
    serialNumber: str = Field(..., description="Serial number of the AGV.")
    orderId: str = Field(
        ...,
        description="Order Identification. This is to be used to identify multiple order messages that belong to the same order.",
    )
    orderUpdateId: conint(ge=0) = Field(
        ...,
        description="orderUpdate identification. Is unique per orderId. If an order update is rejected, this field is to be passed in the rejection message.",
    )
    zoneSetId: Optional[str] = Field(
        None,
        description="Unique identifier of the zone set that the AGV has to use for navigation or that was used by MC for planning.\nOptional: Some MC systems do not use zones. Some AGVs do not understand zones. Do not add to message if no zones are used.",
    )
    nodes: List[Node] = Field(
        ...,
        description="Array of nodes objects to be traversed for fulfilling the order. One node is enough for a valid order. Leave edge list empty for that case.",
    )
    edges: List[Edge] = Field(
        ...,
        description="Directional connection between two nodes. Array of edge objects to be traversed for fulfilling the order. One node is enough for a valid order. Leave edge list empty for that case.",
    )

    def from_json(json_input: json) -> OrderMessage:
        output_order = OrderMessage(
            headerId=json_input["headerId"],
            timestamp=json_input["timestamp"],
            version=json_input["version"],
            manufacturer=json_input["manufacturer"],
            serialNumber=json_input["serialNumber"],
            orderId=json_input["orderId"],
            orderUpdateId=json_input["orderUpdateId"],
            nodes=[],
            edges=[],
        )
        if "zoneSetId" in json_input:
            output_order.zoneSetId = json_input["zoneSetId"]

        for node_json in json_input["nodes"]:
            node = Node(
                nodeId=node_json["nodeId"],
                sequenceId=node_json["sequenceId"],
                released=json.dumps(node_json["released"]),
                actions=[],
            )
            if "nodeDescription" in node_json:
                node.nodeDescription = node_json["nodeDescription"]
            if "nodePosition" in node_json:
                node_position = NodePosition(
                    x=node_json["nodePosition"]["x"],
                    y=node_json["nodePosition"]["y"],
                    mapId=node_json["nodePosition"]["mapId"],
                )
                if "theta" in node_json["nodePosition"]:
                    node_position.theta = node_json["nodePosition"]["theta"]
                else:
                    node_position.theta = 0.0
                if "allowedDeviationXY" in node_json["nodePosition"]:
                    node_position.allowedDeviationXY = node_json["nodePosition"][
                        "allowedDeviationXY"
                    ]
                if "allowedDeviationTheta" in node_json["nodePosition"]:
                    node_position.mapDescription = node_json["nodePosition"][
                        "allowedDeviationTheta"
                    ]
                if "mapDescription" in node_json["nodePosition"]:
                    node_position.mapDescription = node_json["nodePosition"][
                        "mapDescription"
                    ]
                node.nodePosition = node_position
            if "actions" in node_json:
                for action_json in node_json["actions"]:
                    action = Action(
                        actionType=action_json["actionType"],
                        actionId=action_json["actionId"],
                        blockingType=action_json["blockingType"],
                    )
                    if "actionDescription" in action_json:
                        action.actionDescription = action_json["actionDescription"]
                    if "actionParameters" in action_json:
                        action_parameters = []
                        for action_parameter_json in action_json["actionParameters"]:
                            action_parameter = ActionParameter(
                                key=action_parameter_json["key"],
                                value=action_parameter_json["value"],
                            )
                            action_parameters.append(action_parameter)
                        action.actionParameters = action_parameters
                    node.actions.append(action)
            output_order.nodes.append(node)

        for edge_json in json_input["edges"]:
            edge = Edge(
                edgeId=edge_json["edgeId"],
                sequenceId=edge_json["sequenceId"],
                released=json.dumps(edge_json["released"]),
                startNodeId=edge_json["startNodeId"],
                endNodeId=edge_json["endNodeId"],
                actions=[],
            )
            if "edgeDescription" in edge_json:
                edge.edgeDescription = edge_json["edgeDescription"]
            if "maxSpeed" in edge_json:
                edge.maxSpeed = edge_json["maxSpeed"]
            if "maxHeight" in edge_json:
                edge.maxHeight = edge_json["maxHeight"]
            if "minHeight" in edge_json:
                edge.minHeight = edge_json["minHeight"]
            if "orientation" in edge_json:
                edge.orientation = edge_json["orientation"]
            else:
                edge.orientation = 0.0
            if "orientationType" in edge_json:
                edge.orientationType = edge_json["orientationType"]
            if "direction" in edge_json:
                edge.direction = edge_json["direction"]
            if "rotationAllowed" in edge_json:
                edge.rotationAllowed = json.dumps(edge_json["rotationAllowed"])
            if "maxRotationSpeed" in edge_json:
                edge.maxRotationSpeed = edge_json["maxRotationSpeed"]
            if "length" in edge_json:
                edge.length = edge_json["length"]
            if "trajectory" in edge_json:
                edge.trajectory = Trajectory(
                    degree=edge_json["trajectory"]["degree"],
                    knotVector=[],
                    controlPoints=[],
                )
                for knot_vector_json in edge_json["trajectory"]["knotVector"]:
                    edge.trajectory.knotVector.append(knot_vector_json)
                for control_point_json in edge_json["trajectory"]["controlPoints"]:
                    control_point = ControlPoint(
                        x=control_point_json["x"], y=control_point_json["y"]
                    )
                    if "weight" in control_point_json:
                        control_point.weight = control_point_json["weight"]
                    edge.trajectory.controlPoints.append(control_point)
            if "corridor" in edge_json:
                edge.corridor = Corridor(
                    leftWidth=edge_json["corridor"]["leftWidth"],
                    rightWidth=edge_json["corridor"]["rightWidth"],
                )
                if "corridorRefPoint" in edge_json["corridor"]:
                    edge.corridor.corridorRefPoint = edge_json["corridor"][
                        "corridorRefPoint"
                    ]

            if "actions" in edge_json:
                for action_json in edge_json["actions"]:
                    action = Action(
                        actionType=action_json["actionType"],
                        actionId=action_json["actionId"],
                        blockingType=action_json["blockingType"],
                    )
                    if "actionDescription" in action_json:
                        action.actionDescription = action_json["actionDescription"]
                    if "actionParameters" in action_json:
                        action_parameters = []
                        for action_parameter_json in action_json["actionParameters"]:
                            action_parameter = ActionParameter(
                                key=action_parameter_json["key"],
                                value=action_parameter_json["value"],
                            )
                            action_parameters.append(action_parameter)
                        action.actionParameters = action_parameters
                    edge.actions.append(action)
            output_order.edges.append(edge)
        return output_order
