# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/VDA5050/VDA5050/refs/heads/main/json_schemas/state.schema
#   timestamp: 2024-10-22T05:55:28+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field, confloat

import json


class MapStatus(Enum):
    ENABLED = "ENABLED"
    DISABLED = "DISABLED"


class Map(BaseModel):
    mapId: str = Field(
        ...,
        description="ID of the map describing a defined area of the vehicle's workspace.",
    )
    mapVersion: str = Field(..., description="Version of the map.")
    mapDescription: Optional[str] = Field(
        None, description="Additional information on the map."
    )
    mapStatus: MapStatus = Field(
        ...,
        description="Information on the status of the map indicating, if a map version is currently used on the vehicle. ENABLED: Indicates this map is currently active / used on the AGV. At most one map with the same mapId can have its status set to ENABLED.<br>DISABLED: Indicates this map version is currently not enabled on the AGV and thus could be enabled or deleted by request.",
    )


class OperatingMode(Enum):
    AUTOMATIC = "AUTOMATIC"
    SEMIAUTOMATIC = "SEMIAUTOMATIC"
    MANUAL = "MANUAL"
    SERVICE = "SERVICE"
    TEACHIN = "TEACHIN"


class NodePosition(BaseModel):
    x: float
    y: float
    theta: Optional[float] = None
    mapId: str


class NodeState(BaseModel):
    nodeId: str = Field(..., description="Unique node identification")
    sequenceId: int = Field(
        ..., description="sequenceId to discern multiple nodes with same nodeId."
    )
    nodeDescription: Optional[str] = Field(
        None, description="Additional information on the node."
    )
    released: bool = Field(
        ...,
        description="True: indicates that the node is part of the base. False: indicates that the node is part of the horizon.",
    )
    nodePosition: Optional[NodePosition] = Field(
        None,
        description="Node position. The object is defined in chapter 5.4 Topic: Order (from master control to AGV).\nOptional:Master control has this information. Can be sent additionally, e.g., for debugging purposes. ",
    )


class ControlPoint(BaseModel):
    x: float
    y: float
    weight: Optional[float] = Field(
        None,
        description="The weight, with which this control point pulls on the curve.\nWhen not defined, the default will be 1.0.",
    )


class Trajectory(BaseModel):
    degree: int = Field(
        ...,
        description="Defines the number of control points that influence any given point on the curve. Increasing the degree increases continuity. If not defined, the default value is 1.",
    )
    knotVector: List[confloat(ge=0.0, le=1.0)] = Field(
        ...,
        description="Sequence of parameter values that determine where and how the control points affect the NURBS curve. knotVector has size of number of control points + degree + 1",
    )
    controlPoints: List[ControlPoint] = Field(
        ...,
        description="List of JSON controlPoint objects defining the control points of the NURBS, which includes the beginning and end point.",
    )


class EdgeState(BaseModel):
    edgeId: str = Field(..., description="Unique edge identification")
    sequenceId: int = Field(..., description="sequenceId of the edge.")
    edgeDescription: Optional[str] = Field(
        None, description="Additional information on the edge."
    )
    released: bool = Field(
        ...,
        description="True indicates that the edge is part of the base. False indicates that the edge is part of the horizon.",
    )
    trajectory: Optional[Trajectory] = Field(
        None,
        description="The trajectory is to be communicated as a NURBS and is defined in chapter 6.7 Implementation of the Order message.\nTrajectory segments reach from the point, where the AGV starts to enter the edge to the point where it reports that the next node was traversed. ",
    )


class AgvPosition(BaseModel):
    x: float
    y: float
    theta: float
    mapId: str
    mapDescription: Optional[str] = None
    positionInitialized: bool = Field(
        ...,
        description="True: position is initialized. False: position is not initizalized.",
    )
    localizationScore: Optional[confloat(ge=0.0, le=1.0)] = Field(
        None,
        description="Describes the quality of the localization and therefore, can be used, e.g., by SLAM-AGV to describe how accurate the current position information is.\n0.0: position unknown\n1.0: position known\nOptional for vehicles that cannot estimate their localization score.\nOnly for logging and visualization purposes",
    )
    deviationRange: Optional[float] = Field(
        None,
        description="Value for position deviation range in meters. Optional for vehicles that cannot estimate their deviation, e.g., grid-based localization. Only for logging and visualization purposes.",
    )


class Velocity(BaseModel):
    vx: Optional[float] = Field(
        None, description="The AVGs velocity in its x direction"
    )
    vy: Optional[float] = Field(
        None, description="The AVGs velocity in its y direction"
    )
    omega: Optional[float] = Field(
        None, description="The AVGs turning speed around its z axis."
    )


class BoundingBoxReference(BaseModel):
    x: float
    y: float
    z: float
    theta: Optional[float] = Field(
        None,
        description="Orientation of the loads bounding box. Important for tugger, trains, etc.",
    )


class LoadDimensions(BaseModel):
    length: float = Field(
        ..., description="Absolute length of the loads bounding box in meter."
    )
    width: float = Field(
        ..., description="Absolute width of the loads bounding box in meter."
    )
    height: Optional[float] = Field(
        None,
        description="Absolute height of the loads bounding box in meter.\nOptional:\nSet value only if known.",
    )


class Load(BaseModel):
    loadId: Optional[str] = Field(
        None,
        description="Unique identification number of the load (e.g., barcode or RFID). Empty field, if the AGV can identify the load, but did not identify the load yet. Optional, if the AGV cannot identify the load.",
    )
    loadType: Optional[str] = Field(None, description="Type of load.")
    loadPosition: Optional[str] = Field(
        None,
        description="Indicates, which load handling/carrying unit of the AGV is used, e.g., in case the AGV has multiple spots/positions to carry loads. Optional for vehicles with only one loadPosition.",
        examples=["front", "back", "positionC1"],
    )
    boundingBoxReference: Optional[BoundingBoxReference] = Field(
        None,
        description="Point of reference for the location of the bounding box. The point of reference is always the center of the bounding box bottom surface (at height = 0) and is described in coordinates of the AGV coordinate system.",
    )
    loadDimensions: Optional[LoadDimensions] = Field(
        None, description="Dimensions of the loads bounding box in meters."
    )
    weight: Optional[confloat(ge=0.0)] = Field(
        None, description="Absolute weight of the load measured in kg."
    )


class ActionStatus(Enum):
    WAITING = "WAITING"
    INITIALIZING = "INITIALIZING"
    RUNNING = "RUNNING"
    FINISHED = "FINISHED"
    FAILED = "FAILED"


class ActionState(BaseModel):
    actionId: str = Field(
        ..., description="Unique actionId", examples=["blink_123jdaimoim234"]
    )
    actionType: Optional[str] = Field(
        None,
        description="actionType of the action.\nOptional: Only for informational or visualization purposes. Order knows the type.",
    )
    actionDescription: Optional[str] = Field(
        None, description="Additional information on the current action."
    )
    actionStatus: ActionStatus = Field(
        ...,
        description="WAITING: waiting for the trigger (passing the mode, entering the edge) PAUSED: paused by instantAction or external trigger FAILED: action could not be performed.",
    )
    resultDescription: Optional[str] = Field(
        None,
        description="Description of the result, e.g., the result of a RFID-read. Errors will be transmitted in errors.",
    )


class BatteryState(BaseModel):
    batteryCharge: float = Field(
        ...,
        description="State of Charge in %:\nIf AGV only provides values for good or bad battery levels, these will be indicated as 20% (bad) and 80% (good).",
    )
    batteryVoltage: Optional[float] = Field(None, description="Battery voltage")
    batteryHealth: Optional[confloat(ge=0.0, le=100.0)] = Field(
        None, description="State of health in percent."
    )
    charging: bool = Field(
        ...,
        description="True: charging in progress. False: AGV is currently not charging.",
    )
    reach: Optional[confloat(ge=0.0)] = Field(
        None, description="Estimated reach with current State of Charge in meter."
    )


class ErrorReference(BaseModel):
    referenceKey: str = Field(
        ...,
        description="Specifies the type of reference used (e.g. nodeId, edgeId, orderId, actionId, etc.).",
    )
    referenceValue: str = Field(
        ...,
        description="The value that belongs to the reference key. For example, the id of the node where the error occurred.",
    )


class ErrorLevel(Enum):
    WARNING = "WARNING"
    FATAL = "FATAL"


class Error(BaseModel):
    errorType: str = Field(..., description="Type/name of error.")
    errorReferences: Optional[List[ErrorReference]] = None
    errorDescription: Optional[str] = Field(
        None,
        description="Verbose description providing details and possible causes of the error.",
    )
    errorHint: Optional[str] = Field(
        None, description="Hint on how to approach or solve the reported error."
    )
    errorLevel: ErrorLevel = Field(
        ...,
        description="WARNING: AGV is ready to start (e.g., maintenance cycle expiration warning). FATAL: AGV is not in running condition, user intervention required (e.g., laser scanner is contaminated).",
    )


class InfoReference(BaseModel):
    referenceKey: str = Field(
        ...,
        description="References the type of reference (e.g., headerId, orderId, actionId, etc.).",
    )
    referenceValue: str = Field(
        ..., description="References the value, which belongs to the reference key."
    )


class InfoLevel(Enum):
    INFO = "INFO"
    DEBUG = "DEBUG"


class Information(BaseModel):
    infoType: str = Field(..., description="Type/name of information.")
    infoReferences: Optional[List[InfoReference]] = None
    infoDescription: Optional[str] = Field(None, description="Info of description.")
    infoLevel: InfoLevel = Field(
        ..., description="DEBUG: used for debugging. INFO: used for visualization."
    )


class EStop(Enum):
    AUTOACK = "AUTOACK"
    MANUAL = "MANUAL"
    REMOTE = "REMOTE"
    NONE = "NONE"


class SafetyState(BaseModel):
    eStop: EStop = Field(
        ...,
        description="Acknowledge-Type of eStop: AUTOACK: auto-acknowledgeable e-stop is activated, e.g., by bumper or protective field. MANUAL: e-stop hast to be acknowledged manually at the vehicle. REMOTE: facility e-stop has to be acknowledged remotely. NONE: no e-stop activated.",
    )
    fieldViolation: bool = Field(
        ...,
        description="Protective field violation. True: field is violated. False: field is not violated.",
    )


class State(BaseModel):
    headerId: int = Field(
        ...,
        description="headerId of the message. The headerId is defined per topic and incremented by 1 with each sent (but not necessarily received) message.",
    )
    timestamp: datetime = Field(
        ...,
        description="Timestamp in ISO8601 format (YYYY-MM-DDTHH:mm:ss.ffZ).",
        examples=["1991-03-11T11:40:03.12Z"],
    )
    version: str = Field(
        ...,
        description="Version of the protocol [Major].[Minor].[Patch]",
        examples=["1.3.2"],
    )
    manufacturer: str = Field(..., description="Manufacturer of the AGV")
    serialNumber: str = Field(..., description="Serial number of the AGV.")
    maps: Optional[List[Map]] = Field(
        None,
        description="Array of map-objects that are currently stored on the vehicle.",
    )
    orderId: str = Field(
        ...,
        description='Unique order identification of the current order or the previous finished order. The orderId is kept until a new order is received. Empty string ("") if no previous orderId is available. ',
    )
    orderUpdateId: int = Field(
        ...,
        description='Order Update Identification to identify that an order update has been accepted by the AGV. "0" if no previous orderUpdateId is available.',
    )
    zoneSetId: Optional[str] = Field(
        None,
        description="Unique ID of the zone set that the AGV currently uses for path planning. Must be the same as the one used in the order, otherwise the AGV is to reject the order.\nOptional: If the AGV does not use zones, this field can be omitted.",
    )
    lastNodeId: str = Field(
        ...,
        description='nodeID of last reached node or, if AGV is currently on a node, current node (e.g., "node7"). Empty string ("") if no lastNodeId is available.',
    )
    lastNodeSequenceId: int = Field(
        ...,
        description='sequenceId of the last reached node or, if the AGV is currently on a node, sequenceId of current node. "0" if no lastNodeSequenceId is available. ',
    )
    driving: bool = Field(
        ...,
        description="True: indicates that the AGV is driving and/or rotating. Other movements of the AGV (e.g., lift movements) are not included here.\nFalse: indicates that the AGV is neither driving nor rotating ",
    )
    paused: Optional[bool] = Field(
        None,
        description="True: AGV is currently in a paused state, either because of the push of a physical button on the AGV or because of an instantAction. The AGV can resume the order.\nFalse: The AGV is currently not in a paused state.",
    )
    newBaseRequest: Optional[bool] = Field(
        None,
        description="True: AGV is almost at the end of the base and will reduce speed if no new base is transmitted. Trigger for master control to send new base\nFalse: no base update required.",
    )
    distanceSinceLastNode: Optional[float] = Field(
        None,
        description='Used by line guided vehicles to indicate the distance it has been driving past the "lastNodeId".\nDistance is in meters.',
    )
    operatingMode: OperatingMode = Field(
        ..., description="Current operating mode of the AGV."
    )
    nodeStates: List[NodeState] = Field(
        ...,
        description="Array of nodeState-Objects, that need to be traversed for fulfilling the order. Empty list if idle.",
    )
    edgeStates: List[EdgeState] = Field(
        ...,
        description="Array of edgeState-Objects, that need to be traversed for fulfilling the order, empty list if idle.",
    )
    agvPosition: Optional[AgvPosition] = Field(
        None,
        description="Defines the position on a map in world coordinates. Each floor has its own map.",
    )
    velocity: Optional[Velocity] = Field(
        None, description="The AGVs velocity in vehicle coordinates"
    )
    loads: Optional[List[Load]] = Field(
        None,
        description="Loads, that are currently handled by the AGV. Optional: If AGV cannot determine load state, leave the array out of the state. If the AGV can determine the load state, but the array is empty, the AGV is considered unloaded.",
    )
    actionStates: List[ActionState] = Field(
        ...,
        description="Contains a list of the current actions and the actions which are yet to be finished. This may include actions from previous nodes that are still in progress\nWhen an action is completed, an updated state message is published with actionStatus set to finished and if applicable with the corresponding resultDescription. The actionStates are kept until a new order is received.",
    )
    batteryState: BatteryState = Field(
        ..., description="Contains all battery-related information."
    )
    errors: List[Error] = Field(
        ...,
        description="Array of error-objects. All active errors of the AGV should be in the list. An empty array indicates that the AGV has no active errors.",
    )
    information: Optional[List[Information]] = Field(
        None,
        description="Array of info-objects. An empty array indicates, that the AGV has no information. This should only be used for visualization or debugging – it must not be used for logic in master control.",
    )
    safetyState: SafetyState = Field(
        ..., description="Contains all safety-related information."
    )

    def to_json(state: State) -> json:
        output_json = {
            "headerId": state.headerId,
            "timestamp": str(state.timestamp.year)
            + "-"
            + str(state.timestamp.month)
            + "-"
            + str(state.timestamp.day)
            + "T"
            + str(state.timestamp.hour)
            + ":"
            + str(state.timestamp.minute)
            + ":"
            + str(state.timestamp.second)
            + "Z",
            "version": state.version,
            "manufacturer": state.manufacturer,
            "serialNumber": state.serialNumber,
            "orderId": state.orderId,
            "orderUpdateId": state.orderUpdateId,
            "lastNodeId": state.lastNodeId,
            "lastNodeSequenceId": state.lastNodeSequenceId,
            "driving": state.driving,
            "batteryState": {
                "batteryCharge": state.batteryState.batteryCharge,
                "charging": state.batteryState.charging,
            },
            "operatingMode": state.operatingMode.name,
            "safetyState": {
                "eStop": state.safetyState.eStop.name,
                "fieldViolation": state.safetyState.fieldViolation,
            },
        }

        # nodeStates
        node_states = []
        for node_state in state.nodeStates:
            # Required Fields
            node_state_json = {
                "nodeId": node_state.nodeId,
                "released": node_state.released,
                "sequenceId": node_state.sequenceId,
            }

            if node_state.nodeDescription:
                node_state_json["nodeDescription"] = node_state.nodeDescription

            if node_state.nodePosition:
                node_state_json["nodePosition"] = {
                    "x": node_state.nodePosition.x,
                    "y": node_state.nodePosition.y,
                    "mapId": node_state.nodePosition.mapId,
                }
                if node_state.nodePosition.theta:
                    node_state_json["nodePosition"][
                        "theta"
                    ] = node_state.nodePosition.theta
            node_states.append(node_state_json)
        output_json["nodeStates"] = node_states

        # edgeStates
        edge_states = []
        for edge_state in state.edgeStates:
            edge_state_json = {
                "edgeId": edge_state.edgeId,
                "sequenceId": edge_state.sequenceId,
                "released": edge_state.released,
            }
            if edge_state.edgeDescription:
                edge_state_json["edgeDescription"] = edge_state.edgeDescription
            if edge_state.trajectory:
                edge_state_json["trajectory"] = {
                    "degree": 0,
                    "knotVector": edge_state.trajectory.knotVector,
                }
                control_points = []
                for control_point in edge_state.trajectory.controlPoints:
                    control_point_json = {"x": control_point.x, "y": control_point.y}
                    if control_point.weight:
                        control_point_json["weight"] = control_point.weight
                    control_points.append(control_point_json)
                edge_state_json["trajectory"]["controlPoints"] = control_points
            edge_states.append(edge_state_json)
        output_json["edgeStates"] = edge_states

        # actionStates

        action_states = []
        for action_state in state.actionStates:
            action_state_json = {
                "actionId": action_state.actionId,
                "actionStatus": action_state.actionStatus.name,
            }
            if action_state.actionType:
                action_state_json["actionType"] = action_state.actionType
            if action_state.actionDescription:
                action_state_json["actionDescription"] = action_state.actionDescription
            if action_state.resultDescription:
                action_state_json["resultDescription"] = action_state.resultDescription
            action_states.append(action_state_json)
        output_json["actionStates"] = action_states

        # errors
        errors = []

        for error in state.errors:
            error_json = {
                "errorType": error.errorType,
                "errorLevel": error.errorLevel.name,
            }
            if error.errorDescription:
                error_json["errorDescription"] = error.errorDescription
            if error.errorHint:
                error_json["errorHint"] = error.errorHint
            if error.errorReferences:
                error_references = []
                for error_ref in error.errorReferences:
                    error_reference_json = {
                        "referenceKey": error_ref.referenceKey,
                        "referenceValue": error_ref.referenceValue,
                    }
                    error_references.append(error_reference_json)
                error_json["errorReferences"] = error_references
            errors.append(error_json)
        output_json["errors"] = errors

        # Optional Fields
        if state.batteryState.batteryVoltage:
            output_json["batteryState"][
                "batteryVoltage"
            ] = state.batteryState.batteryVoltage

        if state.batteryState.batteryHealth:
            output_json["batteryState"][
                "batteryHealth"
            ] = state.batteryState.batteryHealth

        if state.batteryState.reach:
            output_json["batteryState"]["reach"] = state.batteryState.reach

        if state.zoneSetId:
            output_json["zoneSetId"] = state.zoneSetId

        if state.paused != None:
            output_json["paused"] = state.paused

        if state.distanceSinceLastNode:
            output_json["distanceSinceLastNode"] = state.distanceSinceLastNode

        if state.agvPosition:
            agv_position = {
                "x": state.agvPosition.x,
                "y": state.agvPosition.y,
                "theta": state.agvPosition.theta,
                "positionInitialized": state.agvPosition.positionInitialized,
                "mapId": state.agvPosition.mapId,
            }
            if state.agvPosition.mapDescription:
                agv_position["mapDescription"] = state.agvPosition.mapDescription
            if state.agvPosition.localizationScore:
                agv_position["localizationScore"] = state.agvPosition.localizationScore
            if state.agvPosition.deviationRange:
                agv_position["deviationRange"] = state.agvPosition.deviationRange
            output_json["agvPosition"] = agv_position

        if state.velocity:
            agv_velocity = {}
            if state.velocity.vx:
                agv_velocity["vx"] = state.velocity.vx
            if state.velocity.vy:
                agv_velocity["vy"] = state.velocity.vy
            if state.velocity.omega:
                agv_velocity["omega"] = state.velocity.omega
            output_json["velocity"] = agv_velocity

        # Loads
        loads = []
        if state.loads:
            for load in state.loads:
                load_json = {}
                if load.loadId:
                    load_json["loadId"] = load.loadId
                if load.loadType:
                    load_json["loadType"] = load.loadType
                if load.loadPosition:
                    load_json["loadPosition"] = load.loadPosition
                if load.weight:
                    load["weight"] = load.weight
                if load.boundingBoxReference:
                    bounding_box_reference = {
                        "x": load.boundingBoxReference.x,
                        "y": load.boundingBoxReference.y,
                        "z": load.boundingBoxReference.z,
                    }
                    if load.boundingBoxReference.theta:
                        bounding_box_reference[
                            "theta"
                        ] = load.boundingBoxReference.theta
                    load_json["boundingBoxReference"] = bounding_box_reference
                if load.loadDimensions:
                    load_dimensions = {
                        "length": load.loadDimensions.length,
                        "width": load.loadDimensions.width,
                    }
                    if load.loadDimensions.height:
                        load_dimensions["height"] = load.loadDimensions.height
                loads.append(load_json)

        if len(loads) > 0:
            output_json["loads"] = loads

        # Information
        information = []
        if state.information:
            for info in state.information:
                info_json = {
                    "infoType": info.infoType,
                    "infoLevel": info.infoLevel.name,
                }
                if info.infoDescription:
                    info_json["infoDescription"] = info.infoDescription
                if info.infoReferences:
                    info_references = []
                    for info_reference in info.infoReferences:
                        info_reference_json = {
                            "referenceKey": info_reference.referenceKey,
                            "referenceValue": info_reference.referenceValue,
                        }
                        info_references.append(info_reference_json)
                    info_json["infoReferences"] = info_references
                information.append(info_json)
        if len(information) > 0:
            output_json["information"] = information

        # Maps
        maps = []
        if state.maps:
            for map in state.maps:
                map_json = {
                    "mapId": map.mapId,
                    "mapVersion": map.mapVersion,
                    "mapStatus": map.mapStatus.name,
                }
                if map.mapDescription:
                    map_json["mapDescription"] = map.mapDescription
                maps.append(map_json)
        if len(maps) > 0:
            output_json["maps"] = maps

        return json.loads(json.dumps(output_json, default=str))

    def from_json(json_input: json) -> State:
        output_state = State(
            headerId=json_input["headerId"],
            # EDITED 2026-04-30: Changed format to include milliseconds (.%f) to handle timestamps like "2026-04-30T12:56:02.455Z"
            timestamp=datetime.strptime(
                str(json_input["timestamp"]), "%Y-%m-%dT%H:%M:%S.%fZ"
            ),
            version=json_input["version"],
            manufacturer=json_input["manufacturer"],
            serialNumber=json_input["serialNumber"],
            orderId=json_input["orderId"],
            orderUpdateId=json_input["orderUpdateId"],
            lastNodeId=json_input["lastNodeId"],
            lastNodeSequenceId=json_input["lastNodeSequenceId"],
            driving=json.dumps(json_input["driving"]),
            operatingMode=OperatingMode(json_input["operatingMode"]),
            batteryState=BatteryState(
                batteryCharge=json_input["batteryState"]["batteryCharge"],
                charging=json.dumps(json_input["batteryState"]["charging"]),
            ),
            safetyState=SafetyState(
                eStop=json_input["safetyState"]["eStop"],
                fieldViolation=json_input["safetyState"]["fieldViolation"],
            ),
            nodeStates=[],
            edgeStates=[],
            actionStates=[],
            errors=[],
        )

        for node_state_json in json_input["nodeStates"]:
            node_state = NodeState(
                nodeId=node_state_json["nodeId"],
                sequenceId=node_state_json["sequenceId"],
                released=json.dumps(node_state_json["released"]),
            )
            if "nodeDescription" in node_state_json:
                node_state.nodeDescription = node_state_json["nodeDescription"]
            if "nodePosition" in node_state_json:
                node_state.nodePosition = NodePosition(
                    x=node_state_json["nodePosition"]["x"],
                    y=node_state_json["nodePosition"]["y"],
                    mapId=node_state_json["nodePosition"]["mapId"],
                )
                if "theta" in node_state_json["nodePosition"]:
                    node_state.nodePosition.theta = node_state_json["nodePosition"][
                        "theta"
                    ]
            output_state.nodeStates.append(node_state)

        for edge_state_json in json_input["edgeStates"]:
            edge_state = EdgeState(
                edgeId=edge_state_json["edgeId"],
                sequenceId=edge_state_json["sequenceId"],
                released=json.dumps(edge_state_json["released"]),
            )
            if "edgeDescription" in edge_state_json:
                edge_state.edgeDescription = edge_state_json["edgeDescription"]
            if "trajectory" in edge_state_json:
                edge_state.trajectory = Trajectory(
                    degree=edge_state_json["trajectory"]["degree"],
                    knotVector=edge_state_json["trajectory"]["knotVector"],
                    controlPoints=[],
                )

                for control_point_json in edge_state_json["trajectory"][
                    "controlPoints"
                ]:
                    control_point = ControlPoint(
                        x=control_point_json["x"], y=control_point_json["y"]
                    )
                    if "weight" in control_point_json:
                        control_point.weight = control_point_json["weight"]
                    edge_state.trajectory.controlPoints.append(control_point)
            output_state.edgeStates.append(edge_state)

        for action_state_json in json_input["actionStates"]:
            action_state = ActionState(
                actionId=action_state_json["actionId"],
                actionStatus=action_state_json["actionStatus"],
            )
            if "actionType" in action_state_json:
                action_state.actionType = action_state_json["actionType"]
            if "actionDescription" in action_state_json:
                action_state.actionDescription = action_state_json["actionDescription"]
            if "resultDescription" in action_state_json:
                action_state.resultDescription = action_state_json["resultDescription"]
            output_state.actionStates.append(action_state)

        if "batteryHealth" in json_input["batteryState"]:
            output_state.batteryState.batteryHealth = json_input["batteryState"][
                "batteryHealth"
            ]
        if "batteryVoltage" in json_input["batteryState"]:
            output_state.batteryState.batteryVoltage = json_input["batteryState"][
                "batteryVoltage"
            ]
        if "reach" in json_input["batteryState"]:
            output_state.batteryState.reach = json_input["batteryState"]["reach"]

        for error_json in json_input["errors"]:
            error = Error(
                errorType=error_json["errorType"],
                errorLevel=error_json["errorLevel"],
                errorReferences=[],
            )
            if "errorReferences" in error_json:
                for error_reference in error_json["errorReferences"]:
                    error.errorReferences.append(
                        ErrorReference(
                            referenceKey=error_reference["referenceKey"],
                            referenceValue=error_reference["referenceValue"],
                        )
                    )
            if "errorDescription" in error_json:
                error.errorDescription = error_json["errorDescription"]
            if "errorHint" in error_json:
                error.errorHint = error_json["errorHint"]
            output_state.errors.append(error)

        # Optional
        if "zoneSetId" in json_input:
            output_state.zoneSetId = json_input["zoneSetId"]
        if "paused" in json_input:
            output_state.paused = json.dumps(json_input["paused"])

        if "newBaseRequest" in json_input:
            output_state.newBaseRequest = json_input["newBaseRequest"]

        if "distanceSinceLastNode" in json_input:
            output_state.distanceSinceLastNode = json_input["distanceSinceLastNode"]

        output_state.maps = []
        if "agvPosition" in json_input:
            output_state.agvPosition = AgvPosition(
                x=json_input["agvPosition"]["x"],
                y=json_input["agvPosition"]["y"],
                theta=json_input["agvPosition"]["theta"],
                mapId=json_input["agvPosition"]["mapId"],
                positionInitialized=json.dumps(
                    json_input["agvPosition"]["positionInitialized"]
                ),
            )
            if "mapDescription" in json_input["agvPosition"]:
                output_state.agvPosition.mapDescription = json_input["agvPosition"][
                    "mapDescription"
                ]

            if "localizationScore" in json_input["agvPosition"]:
                output_state.agvPosition.localizationScore = json_input["agvPosition"][
                    "localizationScore"
                ]

            if "deviationRange" in json_input["agvPosition"]:
                output_state.agvPosition.deviationRange = json_input["agvPosition"][
                    "deviationRange"
                ]

        if "velocity" in json_input:
            output_state.velocity = Velocity()
            if "vx" in json_input["velocity"]:
                output_state.velocity.vx
            if "vy" in json_input["velocity"]:
                output_state.velocity.vy
            if "omega" in json_input["velocity"]:
                output_state.velocity.omega

        output_state.loads = []
        if "loads" in json_input:
            for load_json in json_input["loads"]:
                load = Load()
                if "loadId" in load_json:
                    load.loadId = load_json["loadId"]
                if "loadType" in load_json:
                    load.loadType = load_json["loadType"]
                if "loadPosition" in load_json:
                    load.loadPosition = load_json["loadPosition"]
                if "boundingBoxReference" in load_json:
                    load.boundingBoxReference = BoundingBoxReference(
                        x=load_json["boundingBoxReference"]["x"],
                        y=load_json["boundingBoxReference"]["y"],
                        z=load_json["boundingBoxReference"]["z"],
                    )
                    if "theta" in load_json["boundingBoxReference"]:
                        load.boundingBoxReference.theta = load_json[
                            "boundingBoxReference"
                        ]["theta"]
                if "loadDimensions" in load_json:
                    load.loadDimensions = LoadDimensions(
                        length=load_json["loadDimensions"]["length"],
                        width=load_json["loadDimensions"]["width"],
                    )
                    if "height" in load_json["loadDimensions"]:
                        load.loadDimensions.height = load_json["loadDimensions"][
                            "height"
                        ]
                if "weight" in load_json:
                    load.weight = load_json["weight"]
                output_state.loads.append(load)

        output_state.information = []
        if "information" in json_input:
            for info_json in json_input["information"]:
                info = Information(
                    infoType=info_json["infoType"], infoLevel=info_json["infoLevel"]
                )
                if "infoDescription" in info_json:
                    info.infoDescription = info_json["infoDescription"]
                if "infoReferences" in info_json:
                    info.infoReferences = []
                    for info_reference_json in info_json["infoReferences"]:
                        info.infoReferences.append(
                            InfoReference(
                                referenceKey=info_reference_json["referenceKey"],
                                referenceValue=info_reference_json["referenceValue"],
                            )
                        )
                output_state.information.append(info)
        return output_state
