# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2024-12-12T05:17:12+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, Extra, Field
from .CommonClasses import Waypoint, Point2D, Orientation2D
import json


class Type(Enum):
    CommandStatusMessage = "CommandStatusMessage"


class PathItem(BaseModel):
    class Config:
        extra = Extra.forbid

    completed: bool = Field(
        ..., description="Determines if Waypoint has been traversed by the Robot"
    )
    waypoint: Waypoint


class CommandStatusMessage(BaseModel):
    type: Type = Field(
        ..., description="Property. NGSI Entity type. It has to be CommandStatusMessage"
    )
    commandId: str = Field(
        ..., description="Unique ID of the command assigned to the robot"
    )
    robotId: str = Field(..., description="ID of Robot Executing the Command")
    commandStatusTime: str = Field(..., description="Time of Command Status recorded")
    commandUpdateId: int = Field(
        ..., description="Update count of the command assigned to the robot"
    )
    completed: bool = Field(
        ..., description="Determines if the Path has been completed"
    )
    path: List[PathItem] = Field(..., description="Path of Command to Robot")

    def to_json(id: str, input: CommandStatusMessage) -> json:
        output_json = {
            "id": id,
            "type": "CommandStatusMessage",
            "robotId": {"type": "Property", "value": input.robotId},
            "commandId": {"type": "Property", "value": input.commandId},
            "commandStatusTime": {"type": "Property", "value": input.commandStatusTime},
            "commandUpdateId": {
                "type": "Property",
                "value": str(input.commandUpdateId),
            },
            "completed": {"type": "Property", "value": input.completed},
            "path": {"type": "Property", "value": []},
        }
        for path_item in input.path:
            output_json["path"]["value"].append(
                {
                    "completed": json.dumps(path_item.completed),
                    "waypoint": {
                        "nodeId": path_item.waypoint.nodeId,
                        "released": path_item.waypoint.released,
                        "sequenceId": str(path_item.waypoint.sequenceId),
                        "point2D": {
                            "x": path_item.waypoint.point2D.x,
                            "y": path_item.waypoint.point2D.y,
                        },
                        "orientation2D": {
                            "theta": path_item.waypoint.orientation2D.theta
                        },
                    },
                }
            )
        return output_json

    def from_json(input_msg: json) -> CommandStatusMessage:
        output = CommandStatusMessage(
            type="CommandStatusMessage",
            commandId=str(input_msg["commandId"]["value"]),
            robotId=str(input_msg["robotId"]["value"]),
            commandStatusTime=input_msg["commandStatusTime"]["value"],
            commandUpdateId=int(input_msg["commandUpdateId"]["value"]),
            completed=input_msg["completed"]["value"],
            path=[],
        )

        path_array = input_msg["path"]["value"]

        # A bit different for single sized list
        if isinstance(path_array, dict):
            temp = []
            temp.append(path_array)
            path_array = temp

        # Sort the current path to complete based on the Sequence ID
        path_array = sorted(
            path_array,
            key=lambda path_array: path_array["waypoint"]["sequenceId"],
        )
        for path_point in path_array:
            output.path.append(
                PathItem(
                    completed=path_point["completed"],
                    waypoint=Waypoint(
                        nodeId=path_point["waypoint"]["nodeId"],
                        orientation2D=Orientation2D(
                            theta=path_point["waypoint"]["orientation2D"]["theta"]
                        ),
                        point2D=Point2D(
                            x=path_point["waypoint"]["point2D"]["x"],
                            y=path_point["waypoint"]["point2D"]["y"],
                        ),
                        released=path_point["waypoint"]["released"],
                        sequenceId=path_point["waypoint"]["sequenceId"],
                    ),
                )
            )
        return output

    def from_subscriber_json(
        input_msg: json, namespace: str = "ngsi-ld:default-context/"
    ) -> CommandStatusMessage:
        for entry in input_msg["body"]["data"]:
            output = CommandStatusMessage(
                type=entry["type"],
                commandId=str(entry["commandId"]["value"]),
                robotId=str(entry["robotId"]["value"]),
                commandStatusTime=entry["commandStatusTime"]["value"],
                commandUpdateId=int(entry["commandUpdateId"]["value"]),
                completed=json.dumps(entry["completed"]["value"]),
                path=[],
            )

            path_array = entry["path"]["value"]

            # A bit different for single sized list
            if isinstance(path_array, dict):
                temp = []
                temp.append(path_array)
                path_array = temp

            # Sort the current path to complete based on the Sequence ID
            path_array = sorted(
                path_array,
                key=lambda path_array: path_array["waypoint"]["sequenceId"],
            )
            for path_point in path_array:
                output.path.append(
                    PathItem(
                        completed=path_point["completed"],
                        waypoint=Waypoint(
                            nodeId=path_point["waypoint"]["nodeId"],
                            orientation2D=Orientation2D(
                                theta=path_point["waypoint"][
                                    namespace + "orientation2D"
                                ][namespace + "theta"]
                            ),
                            point2D=Point2D(
                                x=path_point["waypoint"][namespace + "point2D"][
                                    namespace + "x"
                                ],
                                y=path_point["waypoint"][namespace + "point2D"][
                                    namespace + "y"
                                ],
                            ),
                            released=json.dumps(path_point["waypoint"]["released"]),
                            sequenceId=int(path_point["waypoint"]["sequenceId"]),
                        ),
                    )
                )
            return output
