# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2024-11-19T04:59:29+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, Extra, Field
from .CommonClasses import Waypoint, Point2D, Orientation2D

import json


class Type(Enum):
    CommandMessage = "CommandMessage"


class CommandMessage(BaseModel):
    type: Type = Field(
        ..., description="Property. NGSI Entity type. It has to be CommandMessage"
    )
    command: str = Field(..., description="Command sent to the robot")
    commandId: str = Field(
        ..., description="Unique ID of the command assigned to the robot"
    )
    commandTime: str = Field(
        ..., description="Sent time to the robot. date-time format"
    )
    commandUpdateId: int = Field(
        ..., description="Update count of the command assigned to the robot"
    )
    waypoints: List[Waypoint] = Field(..., description="List of waypoints")

    def from_json(input_msg: json) -> CommandMessage:
        output = CommandMessage(
            type="CommandMessage",
            commandId=str(input_msg["commandId"]["value"]),
            commandTime=input_msg["commandTime"]["value"],
            command=input_msg["command"]["value"],
            commandUpdateId=int(input_msg["commandUpdateId"]["value"]),
            waypoints=[],
        )
        waypoint_array = input_msg["waypoints"]["value"]

        # A bit different for single sized list
        if isinstance(waypoint_array, dict):
            temp = []
            temp.append(waypoint_array)
            waypoint_array = temp

        # Sort the current path to complete based on the Sequence ID
        waypoint_array = sorted(
            waypoint_array,
            key=lambda waypoint_array: waypoint_array["sequenceId"],
        )

        for waypoint in waypoint_array:
            output.waypoints.append(
                Waypoint(
                    nodeId=waypoint["nodeId"],
                    point2D=Point2D(
                        x=waypoint["point2D"]["x"],
                        y=waypoint["point2D"]["y"],
                    ),
                    orientation2D=Orientation2D(
                        theta=waypoint["orientation2D"]["theta"]
                    ),
                    released=json.loads(waypoint["released"]),
                    sequenceId=waypoint["sequenceId"],
                )
            )

        return output

    def to_json(id: str, input_command: CommandMessage) -> json:
        output_json = {
            "id": id,
            "type": "CommandMessage",
            "commandTime": {"type": "Property", "value": input_command.commandTime},
            "command": {"type": "Property", "value": input_command.command},
            "commandId": {"type": "Property", "value": input_command.commandId},
            "commandUpdateId": {
                "type": "Property",
                "value": input_command.commandUpdateId,
            },
            "waypoints": {"type": "Property", "value": []},
        }
        waypoints = []

        for waypoint in input_command.waypoints:
            waypoints.append(
                {
                    "nodeId": waypoint.nodeId,
                    "point2D": {"x": waypoint.point2D.x, "y": waypoint.point2D.y},
                    "orientation2D": {"theta": waypoint.orientation2D.theta},
                    "released": json.dumps(waypoint.released),
                    "sequenceId": waypoint.sequenceId,
                }
            )

        output_json["waypoints"]["value"] = waypoints
        return output_json

    def from_subscriber_json(input_msg: json, namespace: str):
        namespace = "ngsi-ld:default-context/"
        for entry in input_msg["body"]["data"]:
            output = CommandMessage(
                type="CommandMessage",
                commandId=str(entry["commandId"]["value"]),
                commandTime=entry[namespace + "commandTime"]["value"],
                command=entry[namespace + "command"]["value"],
                commandUpdateId=int(entry["commandUpdateId"]["value"]),
                waypoints=[],
            )

            waypoint_array = entry[namespace + "waypoints"]["value"]

            # A bit different for single sized list
            if isinstance(waypoint_array, dict):
                temp = []
                temp.append(waypoint_array)
                waypoint_array = temp

            # Sort the current path to complete based on the Sequence ID
            waypoint_array = sorted(
                waypoint_array,
                key=lambda waypoint_array: waypoint_array["sequenceId"],
            )

            for waypoint in waypoint_array:
                temp_waypoint = Waypoint(
                    nodeId=waypoint["nodeId"],
                    point2D=Point2D(
                        x=waypoint[namespace + "point2D"][namespace + "x"],
                        y=waypoint[namespace + "point2D"][namespace + "y"],
                    ),
                    orientation2D=Orientation2D(theta=0.0),
                    released=waypoint["released"],
                    sequenceId=waypoint["sequenceId"],
                )
                if (
                    namespace + "orientation2D" in waypoint
                    and namespace + "theta" in waypoint[namespace + "orientation2D"]
                ):
                    temp_waypoint.orientation2D.theta = waypoint[
                        namespace + "orientation2D"
                    ][namespace + "theta"]
                output.waypoints.append(temp_waypoint)
            return output
