# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2024-11-19T04:59:29+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, Extra, Field


class Orientation2D(BaseModel):
    theta: float = Field(..., description="2D Angle of the AGV")


class Point2D(BaseModel):
    x: float = Field(..., description="Property. Simple coordinate of a point")
    y: float = Field(..., description="Property. Simple coordinate of a point")


class Waypoint(BaseModel):
    class Config:
        extra = Extra.forbid

    nodeId: str = Field(..., description="")
    orientation2D: Orientation2D
    point2D: Point2D
    released: bool = Field(
        ..., description="Determines if AGV is allowed to reach this point"
    )
    sequenceId: int = Field(
        ..., description="Sequence ID of the node with respect to the waypoints route"
    )
