# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2024-11-19T04:54:01+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, Extra, Field

from .CommonClasses import Orientation2D, Point2D, Waypoint


import json
import random


class Type(Enum):
    StateMessage = "StateMessage"


class Battery(BaseModel):
    remainingPercentage: int = Field(..., description="Remaining Battery Charge")


class Destination(BaseModel):
    mapId: str = Field(..., description="Map ID")
    nodeId: str = Field(..., description="Corresponding Node ID")
    orientation2D: Orientation2D
    point2D: Point2D
    released: bool = Field(
        ..., description="Determines if AGV is allowed to reach this point"
    )
    sequenceId: int = Field(
        ..., description="Sequence ID of the node with respect to the waypoints route"
    )


class Pose(BaseModel):
    lastNodeSequenceId: int = Field(
        ...,
        description="The last traversed node's sequence ID with respect to the route",
    )
    mapId: str = Field(..., description="Map ID")
    orientation2D: Orientation2D
    point2D: Point2D


class Velocity(BaseModel):
    omega: float = Field(..., description="The AGVs turning speed around its z axis.")
    vx: float = Field(..., description="The AGVs velocity in its x direction")
    vy: float = Field(..., description="The AGVs velocity in its y direction")


class StateMessage(BaseModel):
    type: Type = Field(
        ..., description="Property. NGSI Entity type. It has to be StateMessage"
    )
    battery: Battery
    destination: Destination
    pose: Pose
    velocity: Velocity
    waypoints: List[Waypoint] = Field(..., description="List of waypoints")
    status: str = Field(..., description="State of the AGV")

    def from_json(input_msg: json) -> StateMessage:
        # Parse Waypoints
        waypoints = []
        waypoint_array = input_msg["waypoints"]["value"]

        # A bit different for single sized list
        if isinstance(waypoint_array, dict):
            temp = []
            temp.append(waypoint_array)
            waypoint_array = temp

        # Sort the current path to complete based on the Sequence ID
        waypoint_array = sorted(
            waypoint_array,
            key=lambda waypoint_array: waypoint_array["sequenceId"],
        )
        for waypoint in waypoint_array:
            waypoints.append(
                Waypoint(
                    nodeId=waypoint["nodeId"],
                    point2D=Point2D(
                        x=waypoint["point2D"]["x"],
                        y=waypoint["point2D"]["y"],
                    ),
                    orientation2D=Orientation2D(
                        theta=waypoint["orientation2D"]["theta"]
                    ),
                    released=json.loads(waypoint["released"]),
                    sequenceId=waypoint["sequenceId"],
                )
            )
        return StateMessage(
            type="StateMessage",
            battery=Battery(
                remainingPercentage=input_msg["battery"]["value"]["remainingPercentage"]
            ),
            destination=Destination(
                mapId=input_msg["destination"]["value"]["mapId"],
                nodeId=input_msg["destination"]["value"]["nodeId"],
                orientation2D=Orientation2D(
                    theta=input_msg["destination"]["value"]["orientation2D"]["theta"]
                ),
                point2D=Point2D(
                    x=input_msg["destination"]["value"]["point2D"]["x"],
                    y=input_msg["destination"]["value"]["point2D"]["y"],
                ),
                released=input_msg["destination"]["value"]["released"],
                sequenceId=input_msg["destination"]["value"]["sequenceId"],
            ),
            pose=Pose(
                lastNodeSequenceId=input_msg["pose"]["value"]["lastNodeSequenceId"],
                mapId=input_msg["pose"]["value"]["mapId"],
                orientation2D=Orientation2D(
                    theta=input_msg["pose"]["value"]["orientation2D"]["theta"]
                ),
                point2D=Point2D(
                    x=input_msg["pose"]["value"]["point2D"]["x"],
                    y=input_msg["pose"]["value"]["point2D"]["y"],
                ),
            ),
            velocity=Velocity(
                omega=input_msg["velocity"]["value"]["omega"],
                vx=input_msg["velocity"]["value"]["vx"],
                vy=input_msg["velocity"]["value"]["vy"],
            ),
            waypoints=waypoints,
            status=input_msg["status"]["value"],
        )

    def to_json(id: str, input_msg: StateMessage) -> json:
        output_json = {}
        output_json["id"] = id
        output_json["type"] = "StateMessage"
        output_json["battery"] = {
            "type": "Property",
            "value": {"remainingPercentage": input_msg.battery.remainingPercentage},
        }

        output_json["pose"] = {
            "type": "Property",
            "value": {
                "lastNodeSequenceId": input_msg.pose.lastNodeSequenceId,
                "mapId": input_msg.pose.mapId,
                "orientation2D": {"theta": input_msg.pose.orientation2D.theta},
                "point2D": {
                    "x": input_msg.pose.point2D.x,
                    "y": input_msg.pose.point2D.y,
                },
            },
        }

        output_json["destination"] = {
            "type": "Property",
            "value": {
                "nodeId": input_msg.destination.nodeId,
                "mapId": input_msg.destination.mapId,
                "orientation2D": {"theta": input_msg.destination.orientation2D.theta},
                "point2D": {
                    "x": input_msg.destination.point2D.x,
                    "y": input_msg.destination.point2D.y,
                },
                "released": input_msg.destination.released,
                "sequenceId": input_msg.destination.sequenceId,
            },
        }

        waypoints = []

        for waypoint in input_msg.waypoints:
            waypoint = {
                "point2D": {"x": waypoint.point2D.x, "y": waypoint.point2D.y},
                "orientation2D": {"theta": waypoint.orientation2D.theta},
                "mapId": input_msg.destination.mapId,
                "nodeId": waypoint.nodeId,
                "released": waypoint.released,
                "sequenceId": waypoint.sequenceId,
            }
            waypoints.append(waypoint)

        output_json["waypoints"] = {"type": "Property", "value": waypoints}

        output_json["status"] = {"type": "Property", "value": input_msg.status}

        output_json["velocity"] = {
            "type": "Property",
            "value": {
                "omega": input_msg.velocity.omega,
                "vx": input_msg.velocity.vx,
                "vy": input_msg.velocity.vy,
            },
        }
        return output_json

    def from_subscriber_json(
        input_msg: json, namespace: str = "ngsi-ld:default-context/"
    ) -> StateMessage:
        for entry in input_msg["body"]["data"]:
            battery = Battery(
                remainingPercentage=entry[namespace + "battery"]["value"][
                    namespace + "remainingPercentage"
                ]
            )
            destination = Destination(
                mapId=entry[namespace + "destination"]["value"][namespace + "mapId"],
                nodeId=entry[namespace + "destination"]["value"]["nodeId"],
                orientation2D=Orientation2D(
                    theta=entry[namespace + "destination"]["value"][
                        namespace + "orientation2D"
                    ][namespace + "theta"]
                ),
                point2D=Point2D(
                    x=entry[namespace + "destination"]["value"][namespace + "point2D"][
                        namespace + "x"
                    ],
                    y=entry[namespace + "destination"]["value"][namespace + "point2D"][
                        namespace + "y"
                    ],
                ),
                released=json.dumps(
                    entry[namespace + "destination"]["value"]["released"]
                ),
                sequenceId=entry[namespace + "destination"]["value"]["sequenceId"],
            )
            pose = Pose(
                lastNodeSequenceId=entry[namespace + "pose"]["value"][
                    "lastNodeSequenceId"
                ],
                mapId=entry[namespace + "pose"]["value"][namespace + "mapId"],
                orientation2D=Orientation2D(
                    theta=entry[namespace + "pose"]["value"][
                        namespace + "orientation2D"
                    ][namespace + "theta"]
                ),
                point2D=Point2D(
                    x=entry[namespace + "pose"]["value"][namespace + "point2D"][
                        namespace + "x"
                    ],
                    y=entry[namespace + "pose"]["value"][namespace + "point2D"][
                        namespace + "y"
                    ],
                ),
            )
            velocity = Velocity(
                omega=entry["velocity"]["value"]["omega"],
                vx=entry["velocity"]["value"]["vx"],
                vy=entry["velocity"]["value"]["vy"],
            )
            waypoint_array = entry[namespace + "waypoints"]["value"]

            # A bit different for single sized list
            if isinstance(waypoint_array, dict):
                temp = []
                temp.append(waypoint_array)
                waypoint_array = temp

            # Sort the current path to complete based on the Sequence ID
            waypoint_array = sorted(
                waypoint_array,
                key=lambda waypoint_array: waypoint_array["sequenceId"],
            )
            status = entry["status"]["value"]

            waypoints = []
            for waypoint in waypoint_array:
                temp_waypoint = Waypoint(
                    nodeId=waypoint["nodeId"],
                    point2D=Point2D(
                        x=waypoint[namespace + "point2D"][namespace + "x"],
                        y=waypoint[namespace + "point2D"][namespace + "y"],
                    ),
                    orientation2D=Orientation2D(theta=0.0),
                    released=waypoint["released"],
                    sequenceId=waypoint["sequenceId"],
                )
                if (
                    namespace + "orientation2D" in waypoint
                    and namespace + "theta" in waypoint[namespace + "orientation2D"]
                ):
                    temp_waypoint.orientation2D.theta = waypoint[
                        namespace + "orientation2D"
                    ][namespace + "theta"]
                waypoints.append(temp_waypoint)

            return StateMessage(
                type="StateMessage",
                battery=battery,
                destination=destination,
                pose=pose,
                velocity=velocity,
                waypoints=waypoints,
                status=status,
            )
