# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2025-01-09T06:58:36+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field

import json


class Type(Enum):
    TaskStatus = "TaskStatus"


class Status(Enum):
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    PAUSED = "PAUSED"
    ERROR = "ERROR"
    CANCEL = "CANCEL"


class TaskStatus(BaseModel):
    type: Type = Field(..., description="NGSI Entity type. It has to be TaskStatus")
    id: str = Field(..., description="Task ID")
    taskType: str = Field(..., description="Description of the Task Type")
    taskStart: str = Field(
        ..., description="Start time of the task, defined in the ISO 8601 standard"
    )
    taskEnd: str = Field(
        ..., description="End time of the task, defined in the ISO 8601 standard"
    )
    taskElapsedDuration: str = Field(
        ...,
        description="Total Elapsed time of the task from start time, defined in the ISO 8601 standard",
    )
    status: Status = Field(..., description="Status of the task.")

    def to_json(id: str, input_msg: TaskStatus) -> json:
        return {
            "type": str(Type.TaskStatus.value),
            "id": id,
            "taskType": {"type": "Property", "value": input_msg.taskType},
            "taskStart": {
                "type": "Property",
                "value": input_msg.taskStart,
            },
            "taskEnd": {"type": "Property", "value": input_msg.taskEnd},
            "taskElapsedDuration": {
                "type": "Property",
                "value": input_msg.taskElapsedDuration,
            },
            "status": {
                "type": "Property",
                "value": str(input_msg.status.value),
            },
        }

    def from_subscriber_json(input_msg: json, namespace: str) -> TaskStatus:
        data_json = {}
        for data in input_msg["body"]["data"]:
            data_json = data

        return TaskStatus(
            type=data_json["type"],
            id=data_json["id"].split(":")[-2],
            taskType=data_json["taskType"]["value"],
            taskStart=data_json["taskStart"]["value"],
            taskEnd=data_json["taskEnd"]["value"],
            taskElapsedDuration=data_json["taskElapsedDuration"]["value"],
            status=data_json["status"]["value"],
        )
