# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2025-01-09T06:57:34+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, Field

import json


class Type(Enum):
    Task = "Task"


class TaskCommand(Enum):
    START = "START"
    PAUSE = "PAUSE"
    RESUME = "RESUME"
    CANCEL = "CANCEL"


class TaskRequest(BaseModel):
    type: Type = Field(..., description="NGSI Entity type. It has to be Task")
    id: str = Field(..., description="Task ID")
    taskType: str = Field(..., description="Description of the Task Type")
    taskCommand: TaskCommand = Field(..., description="Description of the Task Type")
    taskParams: List[str] = Field(..., description="List of Task Parameters")
    taskExpectedStart: str = Field(
        ...,
        description="Expected Start time of the task, defined in the ISO 8601 standard",
    )
    taskExpectedEnd: str = Field(
        ...,
        description="Expected End time of the task, defined in the ISO 8601 standard",
    )
    taskExpectedDuration: str = Field(
        ...,
        description="Expected duration of the task, defined in the ISO 8601 standard",
    )

    def from_json(input_json: json) -> TaskRequest:
        output = TaskRequest(
            type=str(Type.Task.value),
            id=input_json["id"],
            taskType=input_json["taskType"]["value"],
            taskCommand=input_json["taskCommand"]["value"],
            taskParams=[],
            taskExpectedStart=input_json["taskExpectedStart"]["value"],
            taskExpectedEnd=input_json["taskExpectedEnd"]["value"],
            taskExpectedDuration=input_json["taskExpectedDuration"]["value"],
        )

        for param in input_json["taskParams"]["value"]:
            output.taskParams.append(param)
        return output

    def from_subscriber_json(input_json: json) -> TaskRequest:
        output = TaskRequest(
            type=str(Type.Task.value),
            id=input_json["id"],
            taskType=input_json["taskType"]["value"],
            taskCommand=input_json["taskCommand"]["value"],
            taskParams=[],
            taskExpectedStart=input_json["taskExpectedStart"]["value"],
            taskExpectedEnd=input_json["taskExpectedEnd"]["value"],
            taskExpectedDuration=input_json["taskExpectedDuration"]["value"],
        )

        param_array = input_json["taskParams"]["value"]

        # A bit different for single sized list
        if isinstance(param_array, dict):
            temp = []
            temp.append(param_array)
            param_array = temp

        for param in param_array:
            output.taskParams.append(param)
        return output

    def to_json(id: str, input_msg: TaskRequest) -> json:
        return {
            "type": str(Type.Task.value),
            "id": id,
            "taskType": {"type": "Property", "value": input_msg.taskType},
            "taskCommand": {
                "type": "Property",
                "value": str(input_msg.taskCommand.value),
            },
            "taskParams": {"type": "Property", "value": input_msg.taskParams},
            "taskExpectedStart": {
                "type": "Property",
                "value": input_msg.taskExpectedStart,
            },
            "taskExpectedEnd": {"type": "Property", "value": input_msg.taskExpectedEnd},
            "taskExpectedDuration": {
                "type": "Property",
                "value": input_msg.taskExpectedDuration,
            },
        }
