# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2024-12-10T06:23:50+00:00

from __future__ import annotations

from enum import Enum
from typing import List

from pydantic import BaseModel, Field

import json


class Type(Enum):
    Map = "Map"


class ConnectedNode(BaseModel):
    nodeID: str = Field(..., description="Node Id of connected node to this Edge")


class Edge(BaseModel):
    edgeId: str = Field(..., description="Edge Id")
    connectedNodes: List[ConnectedNode] = Field(
        ..., description="Array of Nodes this Edge connects"
    )


class Point2D(BaseModel):
    x: float = Field(..., description="X coordinate of Node")
    y: float = Field(..., description="Y cooridinate of Node")


class Node(BaseModel):
    nodeId: str = Field(..., description="Node Id")
    point2D: Point2D = Field(..., description="2D Coordinates of Node")


class Map(BaseModel):
    type: Type = Field(..., description="Property. NGSI Entity type. It has to be Map")
    id: str = Field(..., description="Map Id")
    updateTime: str = Field(
        ..., description="Last Update time of Map. date-time format"
    )
    edges: List[Edge] = Field(
        ..., description="Array of edges that connects nodes in the map"
    )
    nodes: List[Node] = Field(..., description="Array of Nodes in the Map")
    raw: str = Field(
        ..., description="Raw, unparsed string representation of the building"
    )

    def to_json(input_map: Map) -> json:
        output_json = {
            "type": input_map.type.name,
            "id": "urn:ngsi-ld:Map:" + input_map.id,
            "raw": {"type": "Property", "value": input_map.raw},
            "updateTime": {"type": "Property", "value": input_map.updateTime},
            "edges": {"type": "Property", "value": []},
            "nodes": {"type": "Property", "value": []},
        }
        edges = []
        for edge in input_map.edges:
            connected_nodes = []
            for connected_node in edge.connectedNodes:
                connected_nodes.append(connected_node.nodeID)
            edges.append({"edgeId": edge.edgeId, "connectedNodes": connected_nodes})
        output_json["edges"]["value"] = edges

        nodes = []
        for node in input_map.nodes:
            nodes.append(
                {
                    "nodeId": node.nodeId,
                    "point2D": {"x": node.point2D.x, "y": node.point2D.y},
                }
            )
        output_json["nodes"]["value"] = nodes

        return output_json

    def from_json(input_json: json) -> Map:
        edges = []
        for edge in input_json["edges"]["value"]:
            connected_nodes = []
            for connected_node in edge["connectedNodes"]:
                connected_nodes.append(ConnectedNode(nodeID=connected_node))
            edges.append(Edge(edgeId=edge["edgeId"], connectedNodes=connected_nodes))
        nodes = []
        for node in input_json["nodes"]["value"]:
            nodes.append(
                Node(
                    nodeId=node["nodeId"],
                    point2D=Point2D(x=node["point2D"]["x"], y=node["point2D"]["y"]),
                )
            )
        return Map(
            type=input_json["type"],
            id=input_json["id"],
            updateTime=input_json["updateTime"]["value"],
            edges=edges,
            nodes=nodes,
            raw=input_json["raw"]["value"],
        )

    def from_subscriber_json(input_msg: json, namespace: str) -> Map:
        data_json = {}
        for data in input_msg["body"]["data"]:
            data_json = data

        edges = []
        for edge in data_json["edges"]["value"]:
            connected_nodes = []
            for connected_node in edge["connectedNodes"]:
                connected_nodes.append(ConnectedNode(nodeID=connected_node))
            edges.append(Edge(edgeId=edge["edgeId"], connectedNodes=connected_nodes))
        nodes = []
        for node in data_json["nodes"]["value"]:
            nodes.append(
                Node(
                    nodeId=node["nodeId"],
                    point2D=Point2D(
                        x=node[namespace + "point2D"][namespace + "x"],
                        y=node[namespace + "point2D"][namespace + "y"],
                    ),
                )
            )

        return Map(
            type=data_json["type"],
            id=data_json["id"].split(":")[-1],
            updateTime=data_json["updateTime"]["value"],
            edges=edges,
            nodes=nodes,
            raw=data_json["raw"]["value"],
        )
